AWSTemplateFormatVersion: '2010-09-09'
Description: AWS Cloud Formation Stack to Worker Node IAM Role
Parameters:
  EKSWorkerNodeRoleName:
    Description: EKS Worker Node Role Name
    Type: String
    Default: 'EKS-Worker-Node-Role'
    ConstraintDescription: Must be valid EKS Worker Node Role Name
  ApplicationName:
    Description: Application Name
    Type: String
Resources:
  EKSWorkerNodeRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
        - Effect: Allow
          Principal:   
            Service: 
            - ec2.amazonaws.com
          Action: 
          - 'sts:AssumeRole'  
      Path: "/"
      RoleName: !Ref EKSWorkerNodeRoleName         
      ManagedPolicyArns:
      - arn:aws:iam::aws:policy/AmazonEKSWorkerNodePolicy
      - arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy
      - arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryReadOnly
      - arn:aws:iam::aws:policy/CloudWatchAgentServerPolicy
      Tags:
      - Key: Name
        Value: !Ref EKSWorkerNodeRoleName
      - Key: Application Name
        Value: !Ref ApplicationName
  EKSWorkerNodeRoleInstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Path: "/"
      Roles:
      - Ref: EKSWorkerNodeRole